routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use Laravel\Passport\Client;
use Laravel\Passport\ClientRepository;

Route::group(['middleware' => ['force.ssl']], function () {

    Route::get('/', 'WelcomeController@show');
    Route::get('/js/adapter.js', 'WelcomeController@redirectAdapter');
    Route::get('/js/spark-variables.js', 'WelcomeController@sparkVariables');

    Route::get('/home', 'HomeController@show');
    Route::get('/api/v1/teams/{team}/switch', 'HomeController@switchCurrentTeam');

    Route::get('/app', 'HomeController@dashboard');
    Route::get('/app/{path}', 'HomeController@dashboard')->where('path', '.+');
    Route::get('/batches', 'BatchController@index');
    Route::get('/demo', 'DemoController@show');
    Route::get('/test', 'DemoController@test');
    Route::get('/adapter-proxy.js', 'DemoController@adapter');
    Route::get('/importer/{license_key?}', 'ImporterController@show');

    Route::group([
      'prefix' => 'public-api',
      'namespace' => 'PublicApi',
      'middleware' => ['cors', 'validateLicense']
    ], function () {
        Route::apiResource('batches', 'BatchController')->only(['store', 'update']);
        Route::post('batches/{id}/transform-xls', 'BatchController@storeXLS');
        Route::post('batches/{batch}/link-csv', 'BatchController@linkCSV');
        Route::post('batches/{batch}/import-rows', 'BatchController@importRows');
    });
});

/**
 * This handles automatically generating the proper internal login flow for the dashboard.
 */
Route::get('/dashboard-login', function () {
    $in_dev = file_exists(base_path().'/proc/dash');

    $client = Client::where('name', 'Flatfile Dashboard')->where('internal', true)->first();
    $callback_uri = env('DASHBOARD_OAUTH2_CALLBACK', '/app/login-callback');

    if (!$client) {
        $client = Client::create([
            'name' => 'Flatfile Dashboard',
            'internal' => true,
            'secret' => str_random(40),
            'redirect' => $callback_uri,
            'personal_access_client' => false,
            'password_client' => false,
            'revoked' => false
        ]);
    }

    if ($client->redirect != $callback_uri) {
        $client->redirect = $callback_uri;
        $client->save();
    }

    $query = http_build_query([
        'client_id' => $client->id,
        'redirect_uri' => $callback_uri,
        'response_type' => 'token',
        'scope' => '',
    ]);

    return redirect('/oauth/authorize?' . $query);
});

Route::get('/demo-v2', 'WelcomeController@showDemoV2Page');
Route::get('/excel-reader', 'ExcelController@excelReader');
Route::post('/excel-reader', 'ExcelController@excelReader');

app/Models/Batch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\UuidGenerator;
use Carbon\Carbon;

class Batch extends Model
{
    use UuidGenerator;

    protected $dates = ['created_at', 'updated_at', 'matched_at', 'submitted_at', 'failed_at', 'handled_at'];

    protected $casts = [
        'headers_raw' => 'array',
        'headers_matched' => 'array',
        'parsing_config' => 'array'
    ];

    protected $fillable = [
        'filename',
        'end_user_id',
        'original_file',
        'manual',
        'managed',
        'memo',
        'count_rows',
        'count_rows_invalid',
        'count_rows_accepted',
        'count_columns',
        'count_columns_matched',
        'headers_raw',
        'headers_matched',
        'parsing_config',
        'imported_from_url',
        'header_hash',
        'failure_reason',
        'submitted_at',
        'failed_at',
        'created_at',
        'matched_at',
        'handled_at',
        'validated_in',
    ];

    public $incrementing = false;

    public function team()
    {
        return $this->belongsTo(Team::class);
    }

    public function endUser()
    {
        return $this->belongsTo(EndUser::class);
    }

    public function rows()
    {
        return $this->hasMany(Row::class);
    }

    public function uploads()
    {
        return $this->hasMany(Upload::class);
    }

    public function license()
    {
        return $this->belongsTo(License::class);
    }

    public function getStatusAttribute()
    {
        if ($this->failed_at) {
            return 'failed';
        }
        if ($this->handled_at) {
            return 'completed';
        }
        if ($this->submitted_at) {
            return 'submitted';
        }
        if ($this->matched_at && $this->matched_at->diffInMinutes(Carbon::now()) > 30) {
            return 'abandoned';
        }
        if ($this->matched_at) {
            return 'matched';
        }
        if ($this->created_at && $this->created_at->diffInMinutes(Carbon::now()) > 30) {
            return 'abandoned';
        }
        return 'started';
    }

    public function getMatchingTimeAttribute()
    {
        if ($this->submitted_at) {
            return $this->created_at->diffForHumans($this->submitted_at, true);
        }
        return null;
    }

    public function getProcessingTimeAttribute()
    {
        if ($this->submitted_at) {
            return $this->submitted_at->diffForHumans($this->handled_at ?: $this->failed_at, true);
        }
        return null;
    }
}

resources/views/batches.blade.php
@extends('spark::layouts.app')

@section('content')
<home :user="user" inline-template>
    <div class="container-fluid">
        <!-- Application Dashboard -->
        <div class="row">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-header">Batches</div>

                    <div class="card-body">
                        <table class="table table-bordered" style="font-size:12px" id="batches-table" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Filename</th>
                                    {{-- <th>Memo</th> --}}
                                    <th>Uploaded At</th>
                                    <th>Status</th>
                                    <th>Rows</th>
                                    <th>Columns</th>
                                    <th>Matching Time</th>
                                    <th>Processing Time</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($batches as $batch)
                                <tr>
                                    <td><code>{{$batch->filename}}</code></td>
                                    {{-- <td>{{$batch->memo}}</td> --}}
                                    <td data-sort="{{$batch->created_at->timestamp}}">{{$batch->created_at->toDayDateTimeString()}}</td>
                                    <td>{{$batch->status}}</td>
                                    <td data-sort="{{$batch->count_rows}}">{{$batch->count_rows ?number_format($batch->count_rows) : null}}</td>
                                    <td>{{$batch->count_columns}}</td>
                                    <td>{{$batch->matching_time}}</td>
                                    <td>{{$batch->processing_time}}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</home>
@endsection


@section('footer-scripts')
    <script type="text/javascript">
        $(function() {
            $('#batches-table').DataTable();
        })
    </script>
@endsection

resources/views/dashboard.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Flatfile Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @if ($in_dev)
    <script src="http://localhost:4000/flatfile-dashboard/index.js"></script>
    @else
    <script src="/flatfile-dashboard/index.js?cachebust={{time()}}"></script>
    @endif

    <script type="text/javascript">
        window.Spark = <?php echo json_encode(array_merge(
            Spark::scriptVariables(), []
        )); ?>;
    </script>
    <script src="//cdn.headwayapp.co/widget.js"></script>

    <script>
        (function(d) {
        var config = {
            kitId: 'xbq5tas',
            scriptTimeout: 3000,
            async: true
        },
        h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
        })(document);
    </script>
</head>
<body>
    <noscript>Please enable JavaScript to use the Flatfile dashboard.</noscript>
    <div id="app-container"></div>
</body>
</html>

resources/views/home.blade.php
@extends('spark::layouts.app')

@section('content')
<home :user="user" inline-template>
    <div class="container">
        <!-- Application Dashboard -->
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card card-default">
                    <div class="card-header">License Keys</div>

                    <div class="table-responsive">
                        <table class="table table-valign-middle mb-0">
                            <thead>
                            <tr>
                                <th>Team</th>
                                <th>License Key</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($items as $item)
                            <tr>
                                <td>{{$item['team']->name}}</td>
                                <td><code>{{$item['license']->key}}</code></td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</home>
@endsection

resources/views/spark-variables.blade.php
 window.Spark = <?php echo json_encode(array_merge(
    Spark::scriptVariables(), []
)); ?>;

resources/views/test.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta Information -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@yield('title', config('app.name'))</title>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="{{$adapter_url}}"></script>

    <style>
        body, html {
            font-family: "Avenir Next", sans-serif;
            height: 100%;
            margin: 0;
            overflow: hidden;
        }

        .content {
            padding: 20px;
        }

        .full-height {
            min-height: 100%;
        }

        .flex-column {
            display: flex;
            flex-direction: column;
        }

        .flex-fill {
            flex: 1;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }


        .text-center {
            text-align: center;
        }

        .links {
            padding: 1em;
            text-align: right;
        }

        .links a {
            text-decoration: none;
        }

        button {
            background-color: #3097D1;
            border: 0;
            border-radius: 4px;
            color: white;
            cursor: pointer;
            font-size: 14px;
            font-weight: 600;
            padding: 15px;
        }
        iframe  {
            height: 100%;
        }
    </style>
</head>
<body>
    <div class="content">
      <h1>Import your robots!</h1>
      <a href="/downloads/robots.csv">Click here to download a sample CSV file of robots.</a><hr>
      <button id="import-button">Import Robots</button>
      <hr>
      <input type="text" id="filename" />
￼      <hr>
      <textarea id="output" cols="80" rows="20"></textarea>
    </div>
    <script>
        FlatfileImporter.setMountUrl("{!! $in_dev ? env('DEV_IMPORTER_URL', 'http://localhost:2000/theme:simple/?key=:key') : '/importer/:key' !!}")
    </script>

    @if ($config)
      <script>
        var robotImporter = new FlatfileImporter('{{$license_key}}', {!! $config !!})
      </script>

    @else
      <script type="text/javascript">
        var robotImporter = new FlatfileImporter('{{$license_key}}', {
          fields: [{
            label: 'Robot Name',
            key: 'name',
            isRequired: true,
            description: 'The designation of the robot',
            validators: [
              {validate: 'required_without', fields: ['id', 'shield-color'], error: 'must be present if no id or shield color'}
            ],
          }, {
            label: 'Shield Color',
            key: 'shield-color',
            description: 'Chromatic value',
            validator: {
              validate: 'regex_matches',
              regex: /^[a-zA-Z]+$/,
              error: 'Not alphabet only'
            }
          }, {
            label: 'Robot Helmet Style',
            key: 'helmet-style'
          }, {
            label: 'Call Sign',
            key: 'sign',
            alternates: ['nickname', 'wave'],
            validators: [
              {validate: 'regex_matches', regex: /^[a-zA-Z]{4}$/, error: 'must be 4 characters exactly'},
              {validate: 'regex_excludes', regex: /test/, error: 'must not include the word "test"'},
            ],
            isRequired: true
          }, {
            label: 'Robot ID Code',
            key: 'id',
            description: 'Digital identity',
            validators: [
              {validate: 'regex_matches', regex: 'numeric', error: 'must be numeric'},
              {validate: 'required_without', fields: ['name'], error: 'ID must be present if name is absent'}
            ]
          }],
          type: 'Robot',
          // allowInvalidSubmit: true,
          managed: true,
          allowCustom: true
        })
      </script>
    @endif
      <script>
        $(function() {
            // robotImporter.setCustomer({'userId': 'my new user', 'name': 'r2d2'})
            robotImporter.requestDataFromUser().then(function (result) {
                robotImporter.displayLoader()
                setTimeout(function() {
                    robotImporter.displaySuccess()
                    console.log('complete.callback', result)
                    $("#output").val(JSON.stringify(result.validData, null, 2));
                    $("#filename").val(result.filename);
                }, 1500)
            }).catch(function (error) { console.info(error || 'window close') })
            $("#import-button").click(() => {
                robotImporter.requestDataFromUser().then(function (result) {
                    robotImporter.displayLoader()
                    console.log(robotImporter.getMeta())
                    setTimeout(function() {
                        robotImporter.displaySuccess()
                        console.log('complete.callback', result.validData)
                        $("#output").val(JSON.stringify(result.validData, null, 2));
                        $("#filename").val(result.filename);
                    }, 1500)
                }).catch(function (error) { console.info(error || 'window close') })
            })
        })
    </script>
</body>
</html>